### ISSUE TITLE
Add deploy-commands run to github docs

### ISSUE THREAD

**Issue by Aaditya-T** [CR3A7OR/Equestrian-League#1]
https://eql.trioffline.com/doc
I was following this guide and the commands never showed up on server - then i realised i had to run the `deploy-commands` file, i come from discord.py and theres no such thing there so for other developers it might be a bit confusing - can you please add the step to run the deploy-commands in the guide as well? thank you!

<img width="945" alt="image" src="https://github.com/CR3A7OR/Equestrian-League/assets/70804657/5c833ebf-132b-49c4-8197-40568d0d8f60">

**Comment by sp00k5** [comment]
Hey thanks for spotting this, I've made sure to update the documentation accordingly 
 
![image](https://github.com/CR3A7OR/Equestrian-League/assets/67477209/4a69d964-9a5b-4fba-8678-51564e2642cc)
